import type { AgentEvent, AgentStatus, AlertItem, ChartPoint, ClusterNode, PolicyStatus } from "../types/dashboard";

export const fallbackEvents: AgentEvent[] = [
  {
    id: "evt-1",
    timestamp: new Date(Date.now() - 1000 * 60 * 9).toISOString(),
    type: "planner.task_graph.created",
    message: "Planner created task graph for CI validation workflow",
    level: "info",
    metadata: { tasks: 7, agents: 4, workflow: "ci-deploy-184" },
  },
  {
    id: "evt-2",
    timestamp: new Date(Date.now() - 1000 * 60 * 8).toISOString(),
    type: "gpu.request.denied",
    message: "GPU request denied: simple lint task routed to CPU",
    level: "denied",
    metadata: { reason: "low_complexity", estimatedSavings: "$0.42" },
  },
  {
    id: "evt-3",
    timestamp: new Date(Date.now() - 1000 * 60 * 7).toISOString(),
    type: "cache.hit",
    message: "Duplicate embedding job served from Redis cache",
    level: "completed",
    metadata: { cache: "redis", latencyMs: 18 },
  },
  {
    id: "evt-4",
    timestamp: new Date(Date.now() - 1000 * 60 * 6).toISOString(),
    type: "model.routing.optimized",
    message: "Model switched to cheaper LLM for dependency summary",
    level: "approved",
    metadata: { from: "nemotron", to: "small-reasoner", saved: "$1.16" },
  },
  {
    id: "evt-5",
    timestamp: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    type: "policy.command.blocked",
    message: "OpenShell policy blocked destructive command",
    level: "blocked",
    metadata: { command: "rm -rf /", policy: "dangerous_shell_command" },
  },
  {
    id: "evt-6",
    timestamp: new Date(Date.now() - 1000 * 60 * 4).toISOString(),
    type: "gpu.request.approved",
    message: "GPU request approved: Nemotron reasoning for failing tests",
    level: "approved",
    metadata: { model: "Nemotron", gpuUsage: 42, costSaved: 1.9 },
  },
  {
    id: "evt-7",
    timestamp: new Date(Date.now() - 1000 * 60 * 3).toISOString(),
    type: "sandbox.completed",
    message: "Docker sandbox completed test run",
    level: "completed",
    metadata: { tests: "18 passed", runtimeSec: 44 },
  },
  {
    id: "evt-8",
    timestamp: new Date(Date.now() - 1000 * 60 * 2).toISOString(),
    type: "budget.guard.warning",
    message: "Cost threshold warning triggered for training workload",
    level: "warning",
    metadata: { threshold: "$20/hr", current: "$18.80/hr" },
  },
];

export const initialAgents: AgentStatus[] = [
  {
    id: "agent-research-12",
    name: "Research-Agent-12",
    role: "Repository analysis",
    status: "running",
    gpuUsage: 42,
    costPerHour: 3.1,
    currentAction: "Summarizing failing test logs",
    workflow: "ci-deploy-184",
  },
  {
    id: "agent-dev-3",
    name: "Dev-Agent-3",
    role: "Patch generation",
    status: "paused",
    gpuUsage: 0,
    costPerHour: 0,
    currentAction: "Waiting for shell approval",
    workflow: "ci-deploy-184",
  },
  {
    id: "agent-training",
    name: "Training-Agent",
    role: "Model evaluation",
    status: "heavy-load",
    gpuUsage: 96,
    costPerHour: 21,
    currentAction: "Fine-tuning regression evaluator",
    workflow: "eval-nightly-042",
  },
  {
    id: "agent-policy",
    name: "Policy-Guard",
    role: "Safety enforcement",
    status: "running",
    gpuUsage: 0,
    costPerHour: 0,
    currentAction: "Blocking risky tool calls",
    workflow: "all workflows",
  },
  {
    id: "agent-cache",
    name: "Cache-Agent",
    role: "Duplicate detection",
    status: "completed",
    gpuUsage: 0,
    costPerHour: 0,
    currentAction: "Served Redis cache hit",
    workflow: "ci-deploy-184",
  },
];

export const initialChartData: ChartPoint[] = [
  { time: "00:00", gpu: 12, savings: 0, cost: 7.2 },
  { time: "00:01", gpu: 18, savings: 0.22, cost: 7.9 },
  { time: "00:02", gpu: 24, savings: 0.42, cost: 8.4 },
  { time: "00:03", gpu: 31, savings: 0.58, cost: 8.8 },
  { time: "00:04", gpu: 45, savings: 1.16, cost: 10.1 },
  { time: "00:05", gpu: 54, savings: 1.9, cost: 12.4 },
  { time: "00:06", gpu: 39, savings: 2.34, cost: 9.8 },
  { time: "00:07", gpu: 33, savings: 2.76, cost: 8.9 },
];

export const policies: PolicyStatus[] = [
  {
    id: "policy-gpu-limit",
    policy: "GPU Limit Enforcement",
    description: "Caps per-agent GPU allocation and denies low-value GPU requests.",
    status: "active",
    lastTriggered: "2 min ago",
  },
  {
    id: "policy-shell",
    policy: "Dangerous Command Blocking",
    description: "Blocks destructive shell commands before sandbox execution.",
    status: "active",
    lastTriggered: "5 min ago",
  },
  {
    id: "policy-cost",
    policy: "Cost Threshold Alerts",
    description: "Warns when projected spend crosses workflow budget limits.",
    status: "monitoring",
    lastTriggered: "2 min ago",
  },
  {
    id: "policy-internet",
    policy: "Internet Access Control",
    description: "Restricts external network calls unless explicitly approved.",
    status: "active",
    lastTriggered: "No recent trigger",
  },
  {
    id: "policy-idle",
    policy: "Idle Agent Auto-Kill",
    description: "Terminates agents with no useful work after timeout.",
    status: "active",
    lastTriggered: "14 min ago",
  },
];

export const clusterNodes: ClusterNode[] = [
  {
    id: "node-a100-1",
    name: "gpu-node-a100-1",
    gpus: 8,
    usedGpus: 6,
    utilization: 74,
    workloads: 9,
    queue: 3,
    status: "busy",
  },
  {
    id: "node-a100-2",
    name: "gpu-node-a100-2",
    gpus: 8,
    usedGpus: 3,
    utilization: 41,
    workloads: 5,
    queue: 1,
    status: "healthy",
  },
  {
    id: "node-l40-1",
    name: "gpu-node-l40-1",
    gpus: 4,
    usedGpus: 4,
    utilization: 92,
    workloads: 7,
    queue: 6,
    status: "busy",
  },
  {
    id: "cpu-sandbox-1",
    name: "cpu-sandbox-1",
    gpus: 0,
    usedGpus: 0,
    utilization: 36,
    workloads: 12,
    queue: 0,
    status: "healthy",
  },
];

export const alerts: AlertItem[] = [
  {
    id: "alert-1",
    severity: "medium",
    title: "GPU queue rising on l40 pool",
    description: "Queue depth reached 6 while training workload is at 96% utilization.",
    timestamp: new Date(Date.now() - 1000 * 60 * 2).toISOString(),
    status: "watching",
  },
  {
    id: "alert-2",
    severity: "high",
    title: "Risky shell command blocked",
    description: "Policy Guard blocked a destructive OpenShell command before execution.",
    timestamp: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    status: "open",
  },
  {
    id: "alert-3",
    severity: "low",
    title: "Duplicate model call avoided",
    description: "Redis cache served a repeated embedding task, avoiding unnecessary compute.",
    timestamp: new Date(Date.now() - 1000 * 60 * 7).toISOString(),
    status: "resolved",
  },
];

export const costOptimization = {
  computeSavedPercent: 31,
  computeSavedToday: 2.76,
  unnecessaryJobsPrevented: 14,
  cheaperModelsSelected: 6,
  duplicateTasksAvoided: 9,
  projectedMonthlySavings: 842,
};
